version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: worldcup_db
    environment:
      POSTGRES_DB: worldcup2026
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: