# Generated by Django 6.0.4 on 2026-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalties_score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
