name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Rodar um script de teste
        run: echo "O GitHub Actions está funcionando perfeitamente!"